// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebApplicationDemo.Model;

namespace WebApplicationDemo.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230829025207_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClassLibraryCom.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("UserName");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Password");

                    b.Property<int>("Permission")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Permission");

                    b.Property<string>("UserNumber")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UserNumber");

                    b.HasKey("UserName");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
